//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressRanx
    {
        public int AddrRangeID { get; set; }
        public int AssocRoadID { get; set; }
        public int LowerLimit { get; set; }
        public int UpperLimit { get; set; }
        public string AddrRngComment { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual AssociatedRoad AssociatedRoad { get; set; }
    }
}
