//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppErrorLog
    {
        public int EID { get; set; }
        public System.DateTime EDate { get; set; }
        public string EUser { get; set; }
        public string EMessage { get; set; }
        public string ESource { get; set; }
        public int ENo { get; set; }
        public int ESeverity { get; set; }
        public int ELineNo { get; set; }
        public string HostName { get; set; }
    }
}
