//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedRoad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssociatedRoad()
        {
            this.AddressRanges = new HashSet<AddressRanx>();
        }
    
        public int AssocRoadID { get; set; }
        public string RefType { get; set; }
        public int RefID { get; set; }
        public int RoadID { get; set; }
        public decimal MeasureFrom { get; set; }
        public decimal MeasureTo { get; set; }
        public decimal MeasureLength { get; set; }
        public decimal AssocPhaseLength { get; set; }
        public decimal GISLength { get; set; }
        public string FromToDesc { get; set; }
        public int MaintTypeID { get; set; }
        public Nullable<System.DateTime> OrigSurfDate { get; set; }
        public int SurfTypeID { get; set; }
        public string SurfComment { get; set; }
        public Nullable<bool> CurbGutter { get; set; }
        public int WaterSourceID { get; set; }
        public int SewerProviderID { get; set; }
        public string AssocRoadsComment { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressRanx> AddressRanges { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        public virtual MasterRoad MasterRoad { get; set; }
        public virtual LUConsolTable LUConsolTable1 { get; set; }
        public virtual LUConsolTable LUConsolTable2 { get; set; }
        public virtual LUConsolTable LUConsolTable3 { get; set; }
    }
}
