//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSAsBuilt
    {
        public int CSABID { get; set; }
        public int CommSiteID { get; set; }
        public Nullable<System.DateTime> AsBuiltRecvdDate { get; set; }
        public Nullable<System.DateTime> AsBuiltCommDate { get; set; }
        public Nullable<System.DateTime> AsBuiltFinAppvlDate { get; set; }
        public string StructureDesc { get; set; }
        public Nullable<System.DateTime> StorageDate { get; set; }
        public string StorageLoc { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual CommercialSite CommercialSite { get; set; }
    }
}
