//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngSubmittal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngSubmittal()
        {
            this.EngSubComments = new HashSet<EngSubComment>();
        }
    
        public int EngSubmitID { get; set; }
        public string RefType { get; set; }
        public int RefID { get; set; }
        public string RecvdBy { get; set; }
        public string ReceivedFrom { get; set; }
        public Nullable<System.DateTime> RecvdDate { get; set; }
        public int SubmittalTypeID { get; set; }
        public string RoutedTo { get; set; }
        public Nullable<System.DateTime> FinalApprvDate { get; set; }
        public int EngFirmID { get; set; }
        public string EngContactName { get; set; }
        public string EngContactPhone { get; set; }
        public string EngContactFax { get; set; }
        public string EngContactEmail { get; set; }
        public string ProjectName { get; set; }
        public string SubAddr { get; set; }
        public string SubCity { get; set; }
        public string SubST { get; set; }
        public string SubZip { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngSubComment> EngSubComments { get; set; }
        public virtual LUEngFirm LUEngFirm { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
    }
}
