//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUContractorsAudit
    {
        public int ContractorAuditID { get; set; }
        public int ContractorID { get; set; }
        public int ContStatusID { get; set; }
        public string ContractorName { get; set; }
        public string ContractorAddr { get; set; }
        public string ContractorCity { get; set; }
        public string ContractorST { get; set; }
        public string ContractorZip { get; set; }
        public string ContractorPhone { get; set; }
        public Nullable<int> ContractorExt { get; set; }
        public string ContractorFax { get; set; }
        public string ContractorEmail { get; set; }
        public string ContractorComment { get; set; }
        public string ContactName { get; set; }
        public string ContactAddr { get; set; }
        public string ContactCity { get; set; }
        public string ContactST { get; set; }
        public string ContactZip { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> ContactExt { get; set; }
        public string ContactFax { get; set; }
        public string ContactCell { get; set; }
        public string ContactEmail { get; set; }
        public string ContactComment { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual LUConsolTable LUConsolTable { get; set; }
    }
}
