//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUConstInspector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUConstInspector()
        {
            this.CommercialSites = new HashSet<CommercialSite>();
            this.CommercialSitesAudits = new HashSet<CommercialSitesAudit>();
            this.MasterBonds = new HashSet<MasterBond>();
            this.MasterBondsAudits = new HashSet<MasterBondsAudit>();
            this.MasterSubdivs = new HashSet<MasterSubdiv>();
            this.MasterSubdivAudits = new HashSet<MasterSubdivAudit>();
            this.SubdivisionPlats = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlatsAudits = new HashSet<SubdivisionPlatsAudit>();
        }
    
        public int ConstInspID { get; set; }
        public string ConstInspFirstName { get; set; }
        public string ConstInspMidName { get; set; }
        public string ConstInspLastName { get; set; }
        public string ConstInspCode { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSite> CommercialSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSitesAudit> CommercialSitesAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBond> MasterBonds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBondsAudit> MasterBondsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubdiv> MasterSubdivs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubdivAudit> MasterSubdivAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits { get; set; }
    }
}
