//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUConsolTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUConsolTable()
        {
            this.AssociatedRoads = new HashSet<AssociatedRoad>();
            this.AssociatedRoads1 = new HashSet<AssociatedRoad>();
            this.AssociatedRoads2 = new HashSet<AssociatedRoad>();
            this.AssociatedRoads3 = new HashSet<AssociatedRoad>();
            this.EngSubmittals = new HashSet<EngSubmittal>();
            this.LUContractors = new HashSet<LUContractor>();
            this.LUContractorsAudits = new HashSet<LUContractorsAudit>();
            this.LUDevelopers = new HashSet<LUDeveloper>();
            this.LUDevelopersAudits = new HashSet<LUDevelopersAudit>();
            this.MasterBonds = new HashSet<MasterBond>();
            this.MasterBonds1 = new HashSet<MasterBond>();
            this.MasterBonds2 = new HashSet<MasterBond>();
            this.MasterBondsAudits = new HashSet<MasterBondsAudit>();
            this.MasterBondsAudits1 = new HashSet<MasterBondsAudit>();
            this.MasterBondsAudits2 = new HashSet<MasterBondsAudit>();
            this.MasterRoads = new HashSet<MasterRoad>();
            this.MasterRoadsAudits = new HashSet<MasterRoadsAudit>();
            this.MasterSubdivs = new HashSet<MasterSubdiv>();
            this.MasterSubdivAudits = new HashSet<MasterSubdivAudit>();
            this.RespondingAgencies = new HashSet<RespondingAgency>();
            this.Resurfacings = new HashSet<Resurfacing>();
            this.Resurfacings1 = new HashSet<Resurfacing>();
            this.RightOfWays = new HashSet<RightOfWay>();
            this.RoadAliases = new HashSet<RoadAlias>();
            this.Stripings = new HashSet<Striping>();
            this.Stripings1 = new HashSet<Striping>();
            this.Stripings2 = new HashSet<Striping>();
            this.SubdivFees = new HashSet<SubdivFee>();
            this.SubdivisionPlats = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlats1 = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlats2 = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlatsAudits = new HashSet<SubdivisionPlatsAudit>();
            this.SubdivisionPlatsAudits1 = new HashSet<SubdivisionPlatsAudit>();
            this.SubdivisionPlatsAudits2 = new HashSet<SubdivisionPlatsAudit>();
            this.SubdivPermits = new HashSet<SubdivPermit>();
        }
    
        public int ConsolID { get; set; }
        public int TableCatNo { get; set; }
        public string ConsolName { get; set; }
        public string ConsolDesc { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociatedRoad> AssociatedRoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociatedRoad> AssociatedRoads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociatedRoad> AssociatedRoads2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociatedRoad> AssociatedRoads3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngSubmittal> EngSubmittals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUContractor> LUContractors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUContractorsAudit> LUContractorsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUDeveloper> LUDevelopers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUDevelopersAudit> LUDevelopersAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBond> MasterBonds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBond> MasterBonds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBond> MasterBonds2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBondsAudit> MasterBondsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBondsAudit> MasterBondsAudits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBondsAudit> MasterBondsAudits2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterRoad> MasterRoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterRoadsAudit> MasterRoadsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubdiv> MasterSubdivs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubdivAudit> MasterSubdivAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespondingAgency> RespondingAgencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resurfacing> Resurfacings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resurfacing> Resurfacings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RightOfWay> RightOfWays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadAlias> RoadAliases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Striping> Stripings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Striping> Stripings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Striping> Stripings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivFee> SubdivFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivPermit> SubdivPermits { get; set; }
    }
}
