//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUDeveloper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUDeveloper()
        {
            this.CommercialSites = new HashSet<CommercialSite>();
            this.CommercialSitesAudits = new HashSet<CommercialSitesAudit>();
            this.MasterBonds = new HashSet<MasterBond>();
            this.MasterBondsAudits = new HashSet<MasterBondsAudit>();
            this.SubdivisionPlats = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlatsAudits = new HashSet<SubdivisionPlatsAudit>();
        }
    
        public int DeveloperID { get; set; }
        public int DevStatusID { get; set; }
        public string DevName { get; set; }
        public string DevAddr { get; set; }
        public string DevCity { get; set; }
        public string DevST { get; set; }
        public string DevZip { get; set; }
        public string DevFax { get; set; }
        public string DevPhone { get; set; }
        public Nullable<int> DevExt { get; set; }
        public string DevEmail { get; set; }
        public string DevComment { get; set; }
        public string DevContName { get; set; }
        public string DevContAddr { get; set; }
        public string DevContCity { get; set; }
        public string DevContST { get; set; }
        public string DevContZip { get; set; }
        public string DevContFax { get; set; }
        public string DevContPhone { get; set; }
        public Nullable<int> DevContExt { get; set; }
        public string DevContCell { get; set; }
        public string DevContEmail { get; set; }
        public string DevContComment { get; set; }
        public bool CSDev { get; set; }
        public bool PDev { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSite> CommercialSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSitesAudit> CommercialSitesAudits { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBond> MasterBonds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBondsAudit> MasterBondsAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits { get; set; }
    }
}
