//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUEngFirm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUEngFirm()
        {
            this.EngSubmittals = new HashSet<EngSubmittal>();
        }
    
        public int EngFirmID { get; set; }
        public string EngFirmName { get; set; }
        public string EngFirmAddr1 { get; set; }
        public string EngFirmAddr2 { get; set; }
        public string EngFirmCity { get; set; }
        public string EngFirmST { get; set; }
        public string EngFirmZip { get; set; }
        public string EngFirmPhone { get; set; }
        public string EngFirmFax { get; set; }
        public string EngFirmWebsite { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngSubmittal> EngSubmittals { get; set; }
    }
}
