//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LURefType
    {
        public int RefTypeID { get; set; }
        public string RefTypeName { get; set; }
        public string RefTypeDesc { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
    }
}
