//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUSWInspector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUSWInspector()
        {
            this.CommercialSites = new HashSet<CommercialSite>();
            this.CommercialSitesAudits = new HashSet<CommercialSitesAudit>();
            this.SubdivisionPlats = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlatsAudits = new HashSet<SubdivisionPlatsAudit>();
        }
    
        public int SWInspID { get; set; }
        public string SWInspFirstName { get; set; }
        public string SWInspMidName { get; set; }
        public string SWInspLastName { get; set; }
        public string SWInspCode { get; set; }
        public bool CurrRec { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSite> CommercialSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSitesAudit> CommercialSitesAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits { get; set; }
    }
}
