//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBond
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterBond()
        {
            this.BondComments = new HashSet<BondComment>();
        }
    
        public int BondID { get; set; }
        public string RefType { get; set; }
        public int RefID { get; set; }
        public string BondNo { get; set; }
        public int BondTypeID { get; set; }
        public int ConstInspID { get; set; }
        public int BondDescID { get; set; }
        public decimal BondAmt { get; set; }
        public Nullable<System.DateTime> BondBegDate { get; set; }
        public Nullable<System.DateTime> BondExpireDate { get; set; }
        public int BondStatusID { get; set; }
        public System.DateTime BondStatusDate { get; set; }
        public int DeveloperID { get; set; }
        public Nullable<System.DateTime> PunchListDate90 { get; set; }
        public Nullable<System.DateTime> PunchListDate60 { get; set; }
        public Nullable<System.DateTime> PunchListDate30 { get; set; }
        public Nullable<System.DateTime> PunchListDate10 { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<System.DateTime> CoreApprDate { get; set; }
        public Nullable<bool> AddTopReq { get; set; }
        public Nullable<System.DateTime> TopLetterDate { get; set; }
        public string BankName { get; set; }
        public string BankAddr1 { get; set; }
        public string BankAddr2 { get; set; }
        public string BankCity { get; set; }
        public string BankST { get; set; }
        public string BankZip { get; set; }
        public string BankPhone { get; set; }
        public string BankContact { get; set; }
        public string BankContactPh { get; set; }
        public Nullable<int> BankContactExt { get; set; }
        public string BankContactFax { get; set; }
        public string BankContactEmail { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BondComment> BondComments { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        public virtual LUConsolTable LUConsolTable1 { get; set; }
        public virtual LUConsolTable LUConsolTable2 { get; set; }
        public virtual LUConstInspector LUConstInspector { get; set; }
        public virtual LUDeveloper LUDeveloper { get; set; }
    }
}
