//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRoad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterRoad()
        {
            this.AssociatedRoads = new HashSet<AssociatedRoad>();
            this.CulDeSacs = new HashSet<CulDeSac>();
            this.Ratings = new HashSet<Rating>();
            this.RespondingAgencies = new HashSet<RespondingAgency>();
            this.Resurfacings = new HashSet<Resurfacing>();
            this.RoadAliases = new HashSet<RoadAlias>();
            this.RoadComments = new HashSet<RoadComment>();
            this.RoadDistricts = new HashSet<RoadDistrict>();
            this.SpeedLimits = new HashSet<SpeedLimit>();
            this.Stripings = new HashSet<Striping>();
        }
    
        public int RoadID { get; set; }
        public string LocIndicator { get; set; }
        public Nullable<int> RoadPrefixTypeID { get; set; }
        public Nullable<int> RoadPrefixID { get; set; }
        public string RoadName { get; set; }
        public Nullable<int> RoadSuffixTypeID { get; set; }
        public Nullable<int> RoadSuffixID { get; set; }
        public string FullRoadName { get; set; }
        public int RoadStatusID { get; set; }
        public Nullable<System.DateTime> RoadStatusDate { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public string DOTRoadNo { get; set; }
        public Nullable<int> AvgWidthFT { get; set; }
        public Nullable<System.DateTime> LRADate { get; set; }
        public Nullable<bool> GAS { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public Nullable<bool> Cable { get; set; }
        public Nullable<bool> UPower { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociatedRoad> AssociatedRoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CulDeSac> CulDeSacs { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespondingAgency> RespondingAgencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resurfacing> Resurfacings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadAlias> RoadAliases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadComment> RoadComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoadDistrict> RoadDistricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeedLimit> SpeedLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Striping> Stripings { get; set; }
    }
}
