//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRoadsAudit
    {
        public int RoadAuditID { get; set; }
        public int RoadID { get; set; }
        public string LocIndicator { get; set; }
        public Nullable<int> RoadPrefixTypeID { get; set; }
        public Nullable<int> RoadPrefixID { get; set; }
        public string RoadName { get; set; }
        public Nullable<int> RoadSuffixTypeID { get; set; }
        public Nullable<int> RoadSuffixID { get; set; }
        public string FullRoadName { get; set; }
        public int RoadStatusID { get; set; }
        public Nullable<System.DateTime> RoadStatusDate { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public string DOTRoadNo { get; set; }
        public Nullable<int> AvgWidthFT { get; set; }
        public Nullable<System.DateTime> LRADate { get; set; }
        public Nullable<bool> GAS { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public Nullable<bool> Cable { get; set; }
        public Nullable<bool> UPower { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual LUConsolTable LUConsolTable { get; set; }
    }
}
