//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSubdivAudit
    {
        public int MasterSubAuditID { get; set; }
        public int MasterSubID { get; set; }
        public string LocIndicator { get; set; }
        public string MasterSubName { get; set; }
        public Nullable<int> EntranceRoadID { get; set; }
        public int SubStatusID { get; set; }
        public System.DateTime SubStatusDate { get; set; }
        public string LandDistPermNo { get; set; }
        public int ConstInspID { get; set; }
        public bool SidewalksReq { get; set; }
        public Nullable<System.DateTime> ClearGradPermDate { get; set; }
        public decimal TotPropAcreage { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual LUConsolTable LUConsolTable { get; set; }
        public virtual LUConstInspector LUConstInspector { get; set; }
    }
}
