//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSubdiv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterSubdiv()
        {
            this.CommercialSites = new HashSet<CommercialSite>();
            this.CommercialSitesAudits = new HashSet<CommercialSitesAudit>();
            this.MasterSubAliases = new HashSet<MasterSubAlias>();
            this.MasterSubComments = new HashSet<MasterSubComment>();
            this.MasterSubdivZAs = new HashSet<MasterSubdivZA>();
            this.SubdivisionPlats = new HashSet<SubdivisionPlat>();
            this.SubdivisionPlatsAudits = new HashSet<SubdivisionPlatsAudit>();
        }
    
        public int MasterSubID { get; set; }
        public string LocIndicator { get; set; }
        public string MasterSubName { get; set; }
        public Nullable<int> EntranceRoadID { get; set; }
        public int SubStatusID { get; set; }
        public System.DateTime SubStatusDate { get; set; }
        public string LandDistPermNo { get; set; }
        public int ConstInspID { get; set; }
        public bool SidewalksReq { get; set; }
        public Nullable<System.DateTime> ClearGradPermDate { get; set; }
        public decimal TotPropAcreage { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSite> CommercialSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialSitesAudit> CommercialSitesAudits { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        public virtual LUConstInspector LUConstInspector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubAlias> MasterSubAliases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubComment> MasterSubComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSubdivZA> MasterSubdivZAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlat> SubdivisionPlats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubdivisionPlatsAudit> SubdivisionPlatsAudits { get; set; }
    }
}
