//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int RoadID { get; set; }
        public decimal RateFrom { get; set; }
        public decimal RateTo { get; set; }
        public decimal RateLength { get; set; }
        public string FromToDesc { get; set; }
        public int Rating1 { get; set; }
        public System.DateTime RatingDate { get; set; }
        public string RatingComment { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual MasterRoad MasterRoad { get; set; }
    }
}
