//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubdivisionPlatsAudit
    {
        public int MasterPlatAuditID { get; set; }
        public int MasterPlatID { get; set; }
        public int MasterSubID { get; set; }
        public string SubdivPlatName { get; set; }
        public int MaintTypeID { get; set; }
        public Nullable<int> EntranceRoadID { get; set; }
        public int ConstInspID { get; set; }
        public int SWInspID { get; set; }
        public decimal Acreage { get; set; }
        public int BOCDistrictID { get; set; }
        public decimal PlatLength { get; set; }
        public Nullable<System.DateTime> RdConstPermitDate { get; set; }
        public int PlanLocID { get; set; }
        public Nullable<System.DateTime> FinalPlatDate { get; set; }
        public Nullable<System.DateTime> BOCAcceptDate { get; set; }
        public string ClerkOfCtBook { get; set; }
        public string ClerkOfCtPage { get; set; }
        public int PlatStatusID { get; set; }
        public Nullable<bool> ROWWarrDeed { get; set; }
        public Nullable<bool> QuitClaimDeed { get; set; }
        public Nullable<bool> AttorneysTitle { get; set; }
        public Nullable<bool> PerformanceBond { get; set; }
        public Nullable<bool> MaintenanceBond { get; set; }
        public Nullable<bool> PowerCoLetter { get; set; }
        public Nullable<bool> StreetSignPurchVerif { get; set; }
        public Nullable<bool> PropTaxPmtVerif { get; set; }
        public Nullable<bool> IndemnMaintAgreement { get; set; }
        public Nullable<bool> SWFacInspMaintCov { get; set; }
        public Nullable<bool> PT61 { get; set; }
        public Nullable<bool> SetsOfPlans10 { get; set; }
        public Nullable<bool> FCRouteSheet { get; set; }
        public Nullable<bool> HydroStudyNeeded { get; set; }
        public Nullable<bool> BondCalcReq { get; set; }
        public Nullable<bool> CoreResults { get; set; }
        public Nullable<System.DateTime> LegalSentDate { get; set; }
        public Nullable<System.DateTime> DevSentDate { get; set; }
        public Nullable<System.DateTime> StorageDate { get; set; }
        public string StorageLoc { get; set; }
        public string SubNumID { get; set; }
        public int DeveloperID { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual LUBOCDistrict LUBOCDistrict { get; set; }
        public virtual LUConsolTable LUConsolTable { get; set; }
        public virtual LUConsolTable LUConsolTable1 { get; set; }
        public virtual LUConsolTable LUConsolTable2 { get; set; }
        public virtual LUConstInspector LUConstInspector { get; set; }
        public virtual LUDeveloper LUDeveloper { get; set; }
        public virtual LUSWInspector LUSWInspector { get; set; }
        public virtual MasterSubdiv MasterSubdiv { get; set; }
    }
}
