//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubdivFee
    {
        public int SubdivFeeID { get; set; }
        public string RefType { get; set; }
        public int RefID { get; set; }
        public int FeeTypeID { get; set; }
        public decimal FeeAmt { get; set; }
        public Nullable<System.DateTime> FeeCollectedDate { get; set; }
        public string FeeCollectedBy { get; set; }
        public Nullable<int> CheckNo { get; set; }
        public string FeeComment { get; set; }
        public string LCUser { get; set; }
        public System.DateTime LCDate { get; set; }
    
        public virtual LUConsolTable LUConsolTable { get; set; }
    }
}
